[project]
name = "soc_analyst"
version = "0.1.0"
description = "soc_analyst using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.95.0,<1.0.0"
]

[project.scripts]
soc_analyst = "soc_analyst.main:run"
run_crew = "soc_analyst.main:run"
train = "soc_analyst.main:train"
replay = "soc_analyst.main:replay"
test = "soc_analyst.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
